### PR TITLE
adding flavicon, try to change logo

### PR DESCRIPTION
**Pull request by jcolomb**
adding flavicons + new logo

### CODE REVIEW

**Comment by jcolomb** [comment]
some markdown edits were lost in the process (do not know why)

**Comment by jcolomb** [comment]
The logo is not visible, I have no clue why.

**Comment by jcolomb** [comment]
now it works.

**Comment by jcolomb** [comment]
@deeptimittal12 can you check this ? The logos and flavicon are probably not that good though...

**Comment by tamaracha** [comment]
Hi @jcolomb, I assume you mean **favicon**? ;-) Did you try the instructions about [Style customization](https://learn.netlify.app/en/basics/style-customization/) on the theme documentation site, or did you need the header.html for something else? I'm currently rebasing this branch because you merged upstream changes into you local branch which makes the history very intransparent to follow. Have to explain this topic in the wiki probably. Along this line, I can try the instructions from the theme docs and add to this branch. If it looks good, I'll merge the PR.

**Comment by jcolomb** [comment]
Thanks, I did indeed not read the instructions... bad me.

**Pull request merged**
