### PR TITLE
Implement an easier workflow

### PR DESCRIPTION
**Pull request by tamaracha**
This PR tries to implement a (hopefully) easier CI workflow, where it is not strictly necessary to submit formatted files, though it remains a good habit to integrate code formatters and linters locally.

- Mega-linter is dropped because of too much configuration overhead and too many false-positives.
- Pull requests are still checked, but only for semantic or functional issues.
- File formatting is applied via additional commit on push events to the main branch which also triggers when a pr is merged.

### CODE REVIEW

**Comment by jcolomb** [comment]
do I get it correctly that there will be no more commit on PRs ?

That would be a shame, since it is so much better to review things if they went through cleaning first.

**Comment by tamaracha** [comment]
Yes, that would be the implication. The pure prettification would run on the main branch, adding an extra commit containing the formatting changes (if any). After a PR merge one has to pull the main branch anyway, in order to be up-to-date locally. Then you would receive the prettified version. Maybe this “commiting into the pr branch” is more confusing for collaborators because they must fetch and fast-forward the added commits in their pr branch. Besides, it works worse with forks due to access rights. But if I get you right, you would prefer the commits in the pr stage, or just checking everything without any fixup commits?

**Comment by tamaracha** [comment]
By the way, in addition to the text editor integrations, it is also possible to run Prettier [in the browser](https://prettier.io/playground/). Just choose “Markdown” as parser, the remaining options don't matter.

**Comment by jcolomb** [comment]
I am wondering, I liked the idea that the review is done on the edited version of the text, so that one can well suggest change sentence by sentence.
I never thought about making changes locally and push them, after the PR was done.

I think/wonder: what is the usual workflow? Once a PR is done, how much local changes will you do on that same branch, how much GitHub review with single line suggestion would we expect ?

I think this should remain your decision, as you are more experienced in this.

**Pull request closed without merging**
